// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayerService.API.Models;

#nullable disable

namespace PlayerService.API.Migrations
{
    [DbContext(typeof(BaseballDbContext))]
    partial class BaseballDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("PlayerService.API.Models.MlbPlayer", b =>
                {
                    b.Property<int>("MlbPlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MlbTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerFirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerFullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerLastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerNickName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("MlbPlayerId");

                    b.ToTable("MlbPlayer", (string)null);
                });

            modelBuilder.Entity("PlayerService.API.Models.MlbTeam", b =>
                {
                    b.Property<int>("MlbTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamAbbreviation")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamName")
                        .HasColumnType("TEXT");

                    b.HasKey("MlbTeamId");

                    b.ToTable("MlbTeam", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
